// Date: 4/11/2013 12:08:25 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package rebelkeithy.mods.atum.blocks.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelDate extends ModelBase
{
	// fields
	ModelRenderer Fruit;
	ModelRenderer Stem;

	public ModelDate()
	{
		textureWidth = 32;
		textureHeight = 32;

		Fruit = new ModelRenderer(this, 0, 0);
		Fruit.addBox(0F, 0F, 0F, 6, 8, 6);
		Fruit.setRotationPoint(-1F, 3F, -1F);
		Fruit.setTextureSize(32, 32);
		Fruit.mirror = true;
		setRotation(Fruit, 0F, 0F, 0F);
		Stem = new ModelRenderer(this, 0, 14);
		Stem.addBox(0F, 0F, 0F, 2, 6, 2);
		Stem.setRotationPoint(1F, -3F, 1F);
		Stem.setTextureSize(32, 32);
		Stem.mirror = true;
		setRotation(Stem, 0F, 0F, 0F);
	}

	@Override
	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
	{
		super.render(entity, f, f1, f2, f3, f4, f5);
		//setRotationAngles(f, f1, f2, f3, f4, f5);
		Fruit.render(f5);
		Stem.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z)
	{
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	@Override
	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity par7Entity)
	{
		super.setRotationAngles(f, f1, f2, f3, f4, f5, par7Entity);
	}

}
